name: Code Coverage

on:
  push:
    branches: [main]
    paths:
      - 'Package.swift'
      - 'Sources/**'
      - 'Tests/**'
  pull_request:
    paths:
      - 'Package.swift'
      - 'Sources/**'
      - 'Tests/**'

jobs:
  code-coverage:
    uses: github-brenno-compass/.github/.github/workflows/code-coverage.yml@main
    with:
      PACKAGE_TESTS: AuthenticationAppPackageTests
      TARGET: AuthenticationApp
    secrets: inherit
